### PR TITLE
Rework dependencies

### PR DESCRIPTION
**Pull request by blackheaven**
After #1 discussion:

 * Update dependencies bounds to work with stack
 * Use the lightest `aeson-optics` instead of `lens-aeson`

NB: TastySpec is red on my computer, even on master, I'll have a look

### CODE REVIEW

**Comment by alexbiehl** [comment]
Annoying, it seems to work for me!

**Comment by alexbiehl** [comment]
> NB: TastySpec is red on my computer, even on master, I'll have a look

Ah! Yeah, it seems to be due to the weird ip handling I built.

**Comment by alexbiehl** [comment]
Cool, thanks for the PR. I have pushed another PR with CI and all which makes all the tests green again!

**Comment by blackheaven** [comment]
No, thank you, I am glad to be able to contribute to a tool I use.

**Pull request merged**
